[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "shell 'nautilus . > /dev/null 2>&1 &'"
desc = "Run gui file explorer"

[[mgr.prepend_keymap]]
on   = "<C-s>"
run  = "shell 'sesh connect .'" 
desc = "Attach sesh to opened directory"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "." ]
run  = "cd ~/.dotfiles"
desc = "Go to dotfiles repo"

[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd ~/.cache"
desc = "Go to cache dir"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "cd /mnt/log_wymiana"
desc = "Go to log mount"
